/**
 * Bilingual dictionary (EN / FR).
 *
 * This is not decoration. The pilot's central finding is that francophone
 * scholarship is nearly invisible to the infrastructure this project maps
 * (finding 4: French is 2.7% of Canadian metaresearch as OpenAlex sees it;
 * finding 3: Érudit, the principal francophone platform, matches zero OpenAlex
 * sources). An English-only site would refute its own thesis.
 *
 * The French is written, not machine-translated. It uses Canadian francophone
 * LIS/metaresearch vocabulary: métarecherche, notice, moissonnage (OAI-PMH),
 * repérage (retrieval), tri (screening), base de sondage (the frame),
 * estimande, science ouverte, libre accès, les trois organismes (Tri-Agency).
 *
 * NO NUMBERS LIVE HERE. Every figure on the site is read from
 * src/data/findings.json via src/data/findings.ts, so the prose cannot drift
 * from the code that produced it. Strings here describe; they never assert a
 * quantity.
 */

export type Lang = 'en' | 'fr'

export const LANGS: readonly Lang[] = ['en', 'fr'] as const
export const DEFAULT_LANG: Lang = 'en'

export const LANG_LABEL: Record<Lang, string> = {
  en: 'English',
  fr: 'Français',
}

/** BCP-47 tag for the <html lang> attribute. */
export const LANG_TAG: Record<Lang, string> = {
  en: 'en-CA',
  fr: 'fr-CA',
}

export function isLang(v: unknown): v is Lang {
  return v === 'en' || v === 'fr'
}

const en = {
  meta: {
    title: 'MétaCan: a map of Canadian metaresearch',
    description:
      'An open, provenance-tracked, coverage-audited map of Canadian metaresearch. Every record shows why it was found and why it counts as Canadian, and a bilingual human audit quantifies what the pipeline missed.',
  },

  nav: {
    overview: 'Overview',
    findings: 'Findings',
    methods: 'Methods',
    about: 'About',
    primary: 'Primary',
    toggleNav: 'Toggle navigation',
  },

  common: {
    skipToContent: 'Skip to content',
    of: 'of',
    found: 'Retrieved',
    missed: 'Not retrieved',
    source: 'Source',
    consequence: 'Consequence for the design',
    computed: 'Computed',
    caveat: 'Caveat',
    caveatQuoted: 'quoted verbatim from findings.json',
    readMethods: 'Read the method',
    allFindings: 'All findings',
    repository: 'Repository',
    langLabel: 'Language',
    switchToFr: 'Passer au français',
    switchToEn: 'Switch to English',
    /**
     * The label on a struck-through row in a provenance table. The artefact still
     * carries the figure, so the site still shows it; it is no longer a claim, so
     * the site says so. Deleting the row would be the tidier lie.
     */
    withdrawn: 'withdrawn',
    allCorrections: 'All corrections',
    seeFinding: 'See the finding',
  },

  home: {
    eyebrow: 'Canadian Metaresearch Data Challenge · pilot',
    live: 'pilot complete',
    headA: 'A map of Canadian metaresearch,',
    headB: 'honest about what it cannot see.',
    thesis:
      'Every MétaCan record will show why it was found and why it counts as Canadian, and a bilingual human audit will quantify what the pipeline missed.',
    lead:
      'Mapping a research community from bibliographic metadata invites one specific failure: you map what your retrieval could see, then present it as a map of the field. The gap is rarely measured. This project measures it.',
    kpiEyebrow: 'What the pilot measured',
    kpiNote:
      'Every figure on this site is read from pilot/results/findings.json, regenerated by make pilot from API responses archived in the repository. None of it is typed into a page by hand.',
    kpi: {
      topic_route_recall: {
        label: 'Of the field, actually found',
        // {c} is the same route scored against the OTHER screener's labels. It is
        // here because this figure is the one the site leads with, and it is recall
        // against one machine's opinion, not against truth. See finding 15.
        note: 'the topic route missed {a} of {b}; against the other screener, {c}',
      },
      affiliation_gap: {
        label: 'Works with no affiliation',
        note: '{a} of {b} carry no raw affiliation string',
      },
      language_gap: {
        label: 'French share',
        note: '{a} of {b} Canadian works are in French',
      },
      erudit: {
        label: 'Érudit sources in OpenAlex',
        note: '{a} harvestable OAI-PMH sets it cannot see',
      },
    },
    // {n} is filled from FINDINGS.length. The pilot grows; a hard-coded "seven"
    // in this string would be the site's prose drifting from the site's data,
    // which is the failure this entire project is about.
    findingsEyebrow: '{n} analyses against the live OpenAlex API',
    findingsTitle: 'What the pilot found, and what it killed',
    findingsLead:
      'Each analysis was run to see whether the obvious design would work. Most showed that it would not. One killed the coverage estimator this project was originally going to be built on; the last three turn the pipeline’s own instruments back on itself, and measure how much of the field it is missing.',
    seeAll: 'See all findings',
    gapEyebrow: 'The limitation, stated at the top rather than the bottom',
    gapTitle: 'What we cannot see',
    gapTag: 'Out of frame',
    gapLead:
      'Coverage is estimated within a frozen frame of OpenAlex plus Érudit. Scholarship indexed by neither is not estimated by this design, and no claim is made about it. The audit answers a bounded question, honestly answerable, rather than an unbounded one that would require pretending.',
    gapItems: [
      'Scholarship indexed by neither OpenAlex nor Érudit. It is outside the frame, so the audit cannot sample it, and this project does not estimate it.',
      'Work with no affiliation string: the majority of the search space. Affiliation-based country assignment fails on exactly these records, including those of unaffiliated researchers.',
      'Francophone scholarship whose venue OpenAlex does not index. The measured French share describes the pipeline, not the scholarship.',
      'Traditions whose vocabulary the field does not share. An STS ethnography or an LIS study of information behaviour may use none of the keywords and still be squarely in scope.',
    ],
    gapClosing:
      'These are not caveats added at the end. They are the reason the design has a funder clause, an Érudit harvest, a non-retrieved stratum, and a semantic classifier instead of a word list.',
    ctaEyebrow: 'Open by default',
    ctaTitle: 'Run it yourself.\nNo network required.',
    ctaItems: [
      { k: 'Pilot', v: 'make pilot', note: 'against the live OpenAlex API' },
      { k: 'Offline', v: 'make pilot-offline', note: 'from archived raw responses' },
      { k: 'Licence', v: 'MIT · CC BY 4.0', note: 'code · data and docs' },
    ],
  },

  findings: {
    eyebrow: 'Pilot findings',
    title: '{n} analyses, and the design each one forced',
    lead:
      'Every number below is produced by a script in pilot/, run against the live OpenAlex API, with the raw response archived under pilot/raw/. Re-derive them offline, with no network at all, using make pilot-offline. OpenAlex changes daily, so an API query is not a reproducible artefact unless the response itself is kept.',
    barCaption: 'Teal is what the pipeline accounts for. Amber is what it does not.',

    /**
     * The correction. Two sentences, and the figures are injected: {a} is the
     * superseded ratio, derived in findings.ts from the two quantities it wrongly
     * divided, and {b} is the recall that replaces it.
     *
     * A project whose thesis is "measure what you missed" does not get to bury
     * its own miss in a changelog.
     */
    correctionTag: 'Correction',
    correctionA:
      'An earlier version of this site led with {a}: the works the topic route retrieved, divided by the field size the base rate implies.',
    correctionB:
      'That figure was wrong, because a retrieved set and a true field size are not commensurable quantities and the ratio flattered the design; scored directly against the screening rubric, the topic route’s recall is {b}, and its confidence interval excludes the old figure entirely.',

    /** 95% interval on a figure. Both bounds are injected. */
    ci: '95% CI {lo} to {hi}',
    stat: {
      precision: 'Precision',
      // Finding 10 now LEADS with the swap, because agreement sounds like
      // reassurance and the artefact says quoting it alone would be "presenting
      // the reassuring statistic". Agreement is the secondary figure.
      swap: 'Screener swap moves the field by',
      agreement: 'Screeners agree on',
      // Finding 11. These two replace the pair that used to sit here, which
      // reported the adjacent traditions losing several times what core
      // metaresearch loses. That was withdrawn: four works, and an interaction
      // that is not significant. What survives is the main effect, so the main
      // effect is what the card carries.
      noAbstractRate: 'Metaresearch found with no abstract',
      hasAbstractRate: 'With an abstract',
      // Finding 13, the feasibility answer, honestly costed. `designTotal`
      // replaces `stagedTotal`: there are no stages any more, because the
      // prefilter that made them stages has been deleted.
      grantMultiple: 'Times the grant',
      designTotal: 'What the design now costs',
      // Finding 15. The same route, the same works, two machines' labels, and two
      // different answers. The distance between them is the point.
      recallScreenerA: 'Route recall, screener A',
      recallScreenerB: 'Screener B',
    },

    /**
     * A limit one finding places on another, shown on the card of the finding
     * being limited. See Limit in src/data/findings.ts.
     */
    limitTag: 'Limited by finding {n}',
    limit: {
      recallIsModelDependent:
        'This is recall against one screener’s labels, so it measures agreement with a machine rather than accuracy. Scored against the other screener the same route recalls {b}, not {a}. The conclusion holds and hardens, because the second screener thinks the route is worse; the figure does not become a measurement against truth. Only the human-coded probability sample can do that, and it has not run yet.',
    },

    chartEyebrow: 'Finding {n}, drawn out',
    chartTitle: 'Polysemy, term by term',
    chartLead:
      'For each term, the share of its Canadian hits that actually fall in the metaresearch topic space. The everyday sense of a word swamps the metaresearch sense; the more generic the term, the worse it gets. These terms are excluded from the lexicon for that reason.',
    chartAxis: 'On-topic share of hits (%)',
    chartTooltipHits: 'hits alone',
    chartTooltipOnTopic: 'on topic',

    missedEyebrow: 'Finding {n}, drawn out',
    missedTitle: 'Where the missed metaresearch was filed instead',
    missedLead:
      'OpenAlex files a work by what it is about. A metaresearch paper about reporting quality in cardiology trials is, on the page, mostly about cardiology, so it is filed under cardiology and not under scientometrics. The field is invisible to topic-based retrieval precisely because it is about other fields, and the more seriously a study engages the domain it examines, the more surely it disappears into it. These are the fields the missed works were most often filed under instead.',
    missedAxis: 'Metaresearch works the topic route missed',
    missedTooltip: 'missed works, filed here',
    missedNote:
      'The {n} fields above account for {a} of the {b} missed works; the remainder are scattered thinner still. Every one of them is metaresearch, and every one of them was filed as something else.',

    items: {
      topics: {
        title: 'The field has no home in the taxonomy',
        consequence:
          'No single retrieval route can enclose the field. Hence three routes, and record-level provenance for why each work was found.',
        found: 'Topics naming the field',
        missed: 'Topics that do not',
      },
      affiliation_gap: {
        title: 'Affiliation metadata is mostly absent',
        consequence:
          'An affiliation-only rule for "Canadian" is structurally broken, not merely noisy. Hence the funder clause in the primary estimand, and an audit that samples the non-retrieved stratum.',
        found: 'With a raw affiliation string',
        missed: 'With none',
      },
      erudit: {
        title: 'Érudit is invisible to OpenAlex',
        consequence:
          'An OpenAlex-only pipeline cannot even ask how francophone the corpus is. Hence the Érudit OAI-PMH harvest as a first-class source, and language-stratified validation.',
        found: 'Érudit sources matched in OpenAlex',
        missed: 'Harvestable OAI-PMH sets it cannot see',
      },
      language_gap: {
        title: 'Francophone metaresearch is nearly unfindable',
        consequence:
          'The French share is not a fact about Canadian scholarship; it is a fact about the pipeline. Hence French and English performance are reported separately, and French records are oversampled in the audit.',
        found: 'French',
        missed: 'English and other',
      },
      polysemy: {
        title: 'Keyword retrieval cannot survive polysemy',
        consequence:
          'The metaresearch sense of a term is not lexically separable from its everyday sense. Hence semantic screening, and these terms are excluded from the lexicon.',
        found: 'On topic',
        missed: 'Off topic: noise the query cannot filter',
      },
      canadian_linkage: {
        title: '"Canadian" is three different questions',
        consequence:
          'The three senses pick out different sets, and funder metadata skews against the social sciences. Hence one prespecified primary estimand, reported as two components, plus two prespecified alternatives.',
        found: 'Found by Canadian affiliation',
        missed: 'About Canada, with no Canadian affiliation',
      },
      capture_recapture_fails: {
        title: 'Capture–recapture is void here',
        consequence:
          'We ran it, and it fails. The routes are endogenous, so the unseen cell is not identified and the estimate is not even a safe lower bound. It is replaced by a two-phase stratified probability audit that samples the non-retrieved stratum directly instead of inferring it.',
        found: 'Actually observed',
        missed: 'Phantom works the estimator invents',
      },
      openalex_is_metered: {
        title: 'The API is metered, so the frame cannot be enumerated live',
        consequence:
          'A pipeline that re-queries the API at this scale is neither free nor reproducible: one pass over the Canadian frame takes more than a week on the free tier, and the answers change underneath it while it runs. Hence the pinned snapshot, which is both cheap and frozen.',
        found: 'Calls one free rate-limit window buys',
        missed: 'Calls still owed for a single pass',
      },
      base_rate: {
        title: 'The field has a base rate, and therefore a denominator',
        consequence:
          'Screening an unfiltered Canadian sample against the rubric sizes the field without a search strategy at all: a hypothesis with a denominator, which the human-coded probability sample then tests. What it does not do is tell you what retrieval missed. Dividing a retrieved set by this estimate compares unlike things, and an earlier version of this site did exactly that. What retrieval actually missed is measured directly against the rubric, below.',
        found: 'Screened in scope (T1 or T2)',
        missed: 'Screened out',
      },
      agreement: {
        title: 'Swap the screener and the field doubles',
        consequence:
          'Call one model the screener and the base rate is one figure; call the other model the screener and it is more than twice that, which moves the field from tens of thousands of works to tens of thousands more. The published binomial interval does not contain the other model’s estimate, and that is the finding: the uncertainty that matters here is not sampling error, it is which instrument you picked. The two screeners do agree on the great majority of records, but that figure is dominated by the settled rejects and falls exactly on the contested boundary, so it is reported second and never alone. Read the caveat: this measures the screeners, not the truth. Only the human-coded probability sample can do that.',
        found: 'Agreed in / out',
        missed: 'Disagreed: the contested boundary',
      },
      base_rate_robustness: {
        title: 'A third of the frame is screened on its title alone',
        consequence:
          'The obvious objection to the base rate is that its partition is a pile of freshly ingested works, so the rate measures recent research rather than the frame. That objection fails: the partition skews old, and the rate is flat across eras. But era was the wrong covariate. What the partition selects on is abstract recovery, and there the screen is not flat at all: where no abstract exists it finds metaresearch at half the rate, and the effect survives adjustment for publication year and language. A third of the frame is judged on its title alone, and the screen finds half as much there. That is a real coverage problem, and it is why the audit is stratified on abstract availability. Two things this finding used to say, it no longer says. It claimed the blindness was differential by tradition, costing the adjacent traditions several times what it costs core metaresearch, and that claim was this proposal’s whole answer to the inclusiveness criterion; it rests on a cell of four works, the interaction is not significant, and it is withdrawn. It also claimed the abstract-less records were older and less anglophone, which would have made them Érudit’s profile exactly; they are newer, and the stratum is almost entirely English. That sentence is deleted rather than softened. A real coverage problem is not evidence of a differential one, and this finding no longer pretends otherwise. One further limitation belongs to the finding itself rather than to the pipeline: the screening harness silently dropped part of what it was sent, and it dropped it non-randomly on abstract availability, which is the very covariate everything above turns on. The effect is therefore measured on a sample from which abstract-less records were selectively removed, and the direction of that bias is not assumed here.',
        found: 'With an abstract, which the screen can read',
        missed: 'With none, where it finds half as much',
      },
      topic_route_recall: {
        title: 'The field is invisible to topic retrieval, because it is about other fields',
        consequence:
          'Measured directly against the rubric rather than inferred from a ratio, the topic route retrieves a small minority of the metaresearch in the sample, and much of what it does retrieve is not metaresearch at all. It fails for a reason that generalises: OpenAlex files a work by what it is about, so a metaresearch paper on reporting quality in cardiology trials is, on the page, mostly about cardiology, and it is filed there. The more seriously a study engages the domain it examines, the more surely it disappears into it. Hence a design that screens a Canadian frame rather than retrieving a metaresearch one, and that keeps the retrieval routes as provenance rather than promoting them to the gate.',
        found: 'Retrieved by the topic route',
        missed: 'Metaresearch it missed',
      },
      screening_cost: {
        title: 'The prefilter existed because I miscosted the alternative',
        consequence:
          'This finding used to report that screening the whole frame twice against the full rubric cost many times the grant, and that figure is what justified putting a cheap triage in front of the screen. The figure was wrong. The rubric is a system prompt: it is sent once per call, not once per work, and the pilot’s own chunk files batch many works into every call, so the rubric amortises across all of them instead of being charged to each. The cost was overstated several times over. The honest figure leads this card, and it still exceeds the grant, so the second screener still sits on a stratified sample rather than on the frame: finding 10 shows its output is a process metric, and the two things it is for are both sample quantities. Buying precision on a number that is not the estimand is not thrift. What is deleted is the triage. It was never a neutral economy. A prefilter is a retrieval step, and finding 12 is the demonstration that retrieval is exactly what destroys these maps. The earlier version of this card knew that and argued the triage was admissible anyway, on the ground that its recall would be measured rather than hoped for. The argument was sound, and it is now moot: with the arithmetic right, the triage saves almost nothing and buys a retrieval step this project has no business wanting. So the full rubric runs on every work in the frame, the second screener sits on its sample, and what is left over pays the human coder, who is the study. The error was mine; the design it talked me into was mine; both are on the record.',
        found: 'What the grant can pay for',
        missed: 'What screening the frame twice would still owe',
      },
      audit_power: {
        title: 'The audit could not measure the thing it exists to measure',
        consequence:
          'Every other finding here turns the instruments on the pipeline. This one turns them on the validation step, and it fails too. Sampling the rejected mass at random to find what the screen wrongly threw away does not work, because the wrongly rejected are a vanishing fraction of millions of rejects: the budgeted sample expects a fraction of a single hit, and finding enough of them would cost coder-years the grant does not have. Oversampling the records the screener scored near its threshold helps, and it is not enough, because it finds the works the screen almost caught while staying blind to the ones it rejected confidently. Finding 11 names the exposure that is measured: a third of the frame carries no abstract, and there the screen already finds half as much. A work whose title carries none of the field’s vocabulary is rejected confidently rather than narrowly, and that is a mechanism rather than a measured differential; this site claims no more than that, because finding 11’s differential by tradition is withdrawn. The blind spot is still not random, and it is still not where a random sample would look. So recall is measured two other ways instead: against the works that already carry full rubric labels, and by known-item recall on a reference set of venues. Venue is an external criterion. A Canadian-authored paper in a metaresearch journal belongs to the field by where it was published, whatever its abstract appears to be about, which makes venue immune to the aboutness that defeats topic retrieval and title-only screening alike, and the only instrument that can see into the blind spot at all. It is also, as the corrections below record, one of the fields the locked rubric always mandated and the pilot harness silently withheld: this new instrument is in part a proposal to finally do what the rubric said.',
        found: 'Coder-hours the grant pays for',
        missed: 'Coder-hours the naive audit would need',
      },
      label_limits: {
        title: 'The headline is one model’s opinion, and the French stratum holds one work',
        consequence:
          'This finding came from attacking the fixes, and it lands twice. First, on the headline. Finding 14 promoted "score any filter against the works that already carry rubric labels" to a general instrument, and it is a good instrument: it costs nothing and needs no needle-hunting in the discarded mass. But those labels are a machine’s. Scoring against them measures agreement with a machine, not accuracy, and finding 10 already showed that quantity moves by a factor of two when the machine changes. It moves here. The topic route’s recall against the second screener is well below its recall against the first. The conclusion survives and in fact hardens, because the second screener thinks the route is worse; what does not survive is the idea that the figure this site leads with is a measurement against truth. Only the human-coded probability sample reaches truth, and it has not run. Second, and more seriously, on the promise of inclusiveness. The entire pilot contains one French in-scope work. Estimating a French sensitivity would need more coded French records than the audit can buy, so the French stratum is not underpowered; it is unpowered, and no feasible sample size rescues it inside a frame built on OpenAlex alone. That is not a fact about Canadian scholarship, and it must not be read as one. Érudit matches no OpenAlex sources at all, so the francophone literature is not thin in this frame, it is largely absent from it. French power therefore rests entirely on the Érudit harvest, which this pilot verified and did not run. So the French claim is now stated as a condition rather than a promise: if the harvest does not deliver enough French metaresearch to estimate a French sensitivity, the claim is withdrawn rather than fudged. This is the honest state of the inclusiveness criterion, and it is the second time this project has had to revise its answer to that criterion downward.',
        found: 'French records the audit can afford to code',
        missed: 'French records it would still need',
      },
    },
  },

  methods: {
    eyebrow: 'Protocol',
    title: 'The estimand, the frame, the routes, and the audit',
    lead:
      'Preregistration draft, to be registered on OSF before the frame is built and before any retrieval is run. The registration date, the OpenAlex snapshot version, and the Érudit harvest date are stamped at release and cannot be revised afterwards.',

    estimandTitle: 'The estimand, decided in advance',
    estimandLead:
      'The field boundary is contestable. That is a reason to decide in advance and be explicit, not a reason to defer.',
    estimandPrimary: 'Primary: Canadian-produced metaresearch',
    estimandPrimaryBody:
      'A work is in scope if it is screened T1 or T2 and satisfies at least one of: CA-AFF, at least one authorship with an institutional affiliation in Canada; or CA-FUND, at least one funder among CIHR, NSERC, SSHRC, or CFI. The two components are reported separately as well as jointly, because funder metadata skews against the social sciences and a pooled figure would hide that.',
    estimandSecondary: 'Secondary: metaresearch about the Canadian research system',
    estimandSecondaryBody:
      'Irrespective of author location, identified by screening rather than by keyword.',
    estimandDescriptive: 'Descriptive attributes, not inclusion criteria',
    estimandDescriptiveBody:
      'CA-VENUE (published in a Canadian venue, including Érudit-hosted) and CA-PERSON (an author with a known prior Canadian affiliation) are recorded on every record and never used to admit one. A globally generic paper that happens to appear in a Canadian journal is not self-evidently Canadian metaresearch. These are interesting covariates and poor gatekeepers.',
    estimandAlts:
      'Two alternative rules are prespecified to test the consequences of that decision: ALT-1 (strict) is CA-AFF only; ALT-2 (broad) is the primary rule plus CA-VENUE and CA-PERSON. Only these two will be reported. Enumerating every combination of five binary flags is researcher degrees of freedom wearing the costume of a sensitivity analysis.',

    frameTitle: 'The frame (F), frozen before retrieval',
    frameLead:
      'F is defined and frozen before retrieval, and every claim in this study is bounded to F.',
    frameSources: 'Sources',
    frameSourcesBody:
      'A pinned OpenAlex snapshot (not the live API, which changes daily and would make the study unreproducible), plus a pinned Érudit OAI-PMH harvest, with the harvest date stamped.',
    frameWindow: 'Window',
    frameWindowBody: 'Publication years 2000–2025 inclusive.',
    frameMembership: 'Membership',
    frameMembershipBody:
      'A record enters F if it satisfies any of: a Canadian affiliation; a Canadian funder; a mention of Canada in title or abstract, in English or French; any candidate topic; a match on the bilingual lexicon; authorship by a seed-set author; or being an Érudit record.',
    frameWhy:
      'F is deliberately over-broad and low-precision by design. Its purpose is not to be the answer; it is to be an enumerable universe within which the non-retrieved stratum can be sampled. A frame that is merely "all of OpenAlex" cannot be sampled usefully, and a frame that equals the retrieved set cannot measure what retrieval missed.',

    routesTitle: 'Three routes, with provenance',
    routesLead:
      'No single route encloses the field, so each record stores the set of routes that retrieved it. Route overlap and incremental yield are reported descriptively. They are not used to estimate the unseen population.',
    routes: [
      {
        id: 'R1',
        name: 'Structured',
        body: 'Candidate topics and a curated venue list, English and francophone.',
      },
      {
        id: 'R2',
        name: 'Lexical and semantic',
        body: 'A bilingual lexicon, plus multilingual embedding similarity to the seed corpus. Cross-lingual by construction: the actual answer to French, not a word list bolted onto an English one.',
      },
      {
        id: 'R3',
        name: 'Snowball',
        body: 'Curated seed works, plus their citation neighbours, backward and forward.',
      },
    ],

    tiersTitle: 'Screening tiers',
    tiersLead:
      'The question is whether the object of study is research itself. A cardiology trial is not metaresearch. A study of how cardiology trials report their outcomes is. The test is what the work is about, not what field it appears in and not what vocabulary it uses.',
    tiers: [
      {
        id: 'T1',
        name: 'Core metaresearch',
        body: 'The primary object of study is research itself: its methods, reporting, reproducibility, integrity, peer review, evaluation, funding, workforce, scholarly communication (publishing models, open access, open science, preprints), or evidence-synthesis methodology.',
      },
      {
        id: 'T2',
        name: 'Adjacent',
        body: 'Work on science as a social system that is not framed as metaresearch but studies it: science and technology studies, library and information science, research infrastructure, research policy. T2 is where the field’s diversity lives. Be generous here.',
      },
      {
        id: 'T3',
        name: 'Contextual',
        body: 'Editorials, commentary, policy documents, infrastructure announcements. Mapped and released, never pooled into the analytic corpus.',
      },
      {
        id: 'OUT',
        name: 'Not metaresearch',
        body: 'Everything else. A study that uses a method is not a study of the method: a meta-analysis answering a clinical question is out; a study of how meta-analyses handle heterogeneity is T1.',
      },
    ],
    errorsTitle: 'The three errors that matter most',
    errors: [
      {
        name: 'Polysemy',
        body: 'In a biochemistry paper, "reproducibility" means the assay gives the same reading twice. In a metaresearch paper it means the reproducibility crisis. Only the second is in scope. Judge the sense, not the token.',
      },
      {
        name: 'Method versus object',
        body: 'Using bibliometrics is not the same as studying research. Ask what we know more about if this paper is right: a scientific question, or the practice of science? If the former, it is out.',
      },
      {
        name: 'Absence of vocabulary is not absence of content',
        body: 'An STS paper about laboratory practice, or an LIS paper about how researchers find data, may use none of the field’s keywords and still be squarely T2. Do not require the vocabulary. This is the error that makes the field look smaller and more anglophone than it is.',
      },
    ],

    auditTitle: 'Validation: a two-phase stratified probability audit',
    auditLead:
      'The core of the study, and the thing the field usually skips. Capture–recapture is not used, and that is a considered decision rather than an oversight.',
    auditSteps: [
      {
        n: 'Phase 1',
        name: 'Partition and sample',
        body: 'Partition F into retrieved and non-retrieved. Draw a stratified probability sample from both, with known, recorded selection probabilities. Strata cross language, source, partition, and classifier score band. Oversample French records, Érudit records, adjacent STS and LIS material, high-scoring non-retrieved records (where the misses concentrate), and under-represented provinces and genres.',
      },
      {
        n: 'Phase 2',
        name: 'Code, blind, adjudicate',
        body: 'Two coders code each sampled record independently, blind to the classifier score and to each other, against a locked rubric. Disagreements are adjudicated against the rubric and the decisions logged. The classifier plays no part in constructing the reference standard that judges it. The second coder must be bilingual for the French stratum; if no francophone coder is recruited, the French-stratum estimates are withdrawn, not imputed.',
      },
      {
        n: 'Estimate',
        name: 'Design-weighted',
        body: 'Using inverse-selection-probability weights: retrieval sensitivity within F (the headline quantity, and the answer to "what did we miss?"); screening precision and recall with confusion-matrix counts; the eligible count within F with a confidence interval; and differential error by language, source, tradition, genre, and linkage type. That last one is the point: for whom the pipeline fails, not merely how often.',
      },
    ],
    crTitle: 'Why capture–recapture was cut',
    crBody:
      'The routes are endogenous. Snowballing depends on the seed set, and any author-based expansion depends on authors surfaced by the other routes. Log-linear multi-list models cannot identify the all-zero cell without an untestable restriction on the highest-order interaction, and with endogenously constructed lists that restriction is not credible. Nor is the estimate a safe lower bound: depending on the dependence structure it may overstate the unseen population as readily as understate it. The naive estimator returns a figure implying Canada produces the majority of the world’s metaresearch. The only unconditional lower bound on the population is the number of eligible works actually observed, and that is what will be reported. The audit replaces the estimator because it samples the gap instead of inferring it.',
    /**
     * The corrections.
     *
     * Not an apology, and not buried. The protocol (§9) requires every departure
     * to be recorded with a reason and a date, on the ground that silent revision
     * is itself a research-integrity failure. A project whose thesis is "measure
     * what you missed" that quietly fixed its own misses would be refuting itself
     * in public, so this is a numbered section of the method, in the same voice as
     * the rest of it.
     *
     * The figures come from findings.json, including the ones being withdrawn. See
     * CORRECTIONS in src/data/findings.ts.
     */
    correctionsTitle: 'Corrections',
    correctionsLead:
      'Every error found in this project is recorded in DEVIATIONS.md, before submission, with the date it was found and what was done about it. The protocol requires it: silent revision is itself a research-integrity failure, and this is a metaresearch project. The six below are the ones a reader of this site would otherwise have taken on trust, so they are listed here rather than left in a file nobody opens. Each was found by adversarial review or by the project’s own instruments, and none has been quietly rolled into a rewrite.',
    correctionsLinkNote: 'every deviation, with its date and its reason',
    correctionsTag: 'Corrected',
    correctionsClosing:
      'Two of these changed the design rather than the prose. The cost error is what put a cheap prefilter in front of the screen, and deleting the error deleted the prefilter. The rubric violation means the pilot’s numbers came from a screen that saw six of the eight fields its own instrument mandates, so the full study re-runs the screen with the complete payload and reports the difference between the two runs as a finding: what the withheld metadata was worth. That is a measurement nobody normally gets to make, and it exists only because the bug did.',
    correctionsItems: {
      coverage: {
        title: 'The coverage figure this site led with',
        body: 'The pilot reported {a}: the works the topic route retrieved, divided by the field size the base rate implies. That divides a retrieved set by a true field size. They are not commensurable, the retrieved set is neither wholly metaresearch nor a random draw from the field, and the ratio had no estimand behind it. It flattered the design, which is how it survived as long as it did. The right quantity is recall, measured directly against the rubric labels: {b}, whose interval excludes the old figure entirely.',
      },
      differential: {
        title: 'The differential penalty on the adjacent traditions',
        body: 'The screen was said to lose the adjacent traditions (STS, library and information science) at {a}, against core metaresearch at {b}. This was the proposal’s entire answer to the inclusiveness criterion: unable to represent the field’s traditions, I could at least measure how badly I served them. The cell it rests on holds {c} works, and the interaction test, which is the only test that asks whether the two penalties differ at all, gives p = {d}. They cannot be told apart. The differential claim is withdrawn. The main effect it was built on survives, and is a real coverage problem, but it is not evidence of differential blindness by tradition.',
      },
      erudit_profile: {
        title: '"Missing abstracts track older, non-English records: Érudit’s exact profile"',
        body: 'Backwards on both counts. The abstract-less works are newer, not older ({b} against {c}), and the stratum is {a} English, so English-language works are the ones more likely to lack an abstract ({d} against {e}). The sentence inferred a francophone platform’s signature from an almost entirely anglophone stratum. It was also hard-coded as prose in a script whose own comment, three lines above, called hard-coding such a direction indefensible in a metaresearch project. The sentence is deleted, not softened.',
      },
      cost: {
        title: 'The screening cost, and the prefilter it bought',
        body: 'Screening the frame twice against the full rubric was costed at {a} by charging the rubric once per work. The rubric is a system prompt, sent once per call, and the pilot’s own chunk files batch many works into each call, so it amortises across them: the bill was overstated {c}. The honest figure is {b}. The error was not cosmetic. It is what justified a cheap triage in front of the screen, and a triage is a retrieval step in a project whose central finding is that retrieval is what destroys these maps. With the arithmetic right, the triage saves almost nothing. It is deleted, and the full rubric now runs on every work in the frame, with the second screener on a sample, for {d}.',
      },
      audit: {
        title: 'The audit design could not measure what an audit measures',
        body: 'Validation was to sample the screened-out mass at random and count what the screen wrongly rejected. Those works are a vanishing fraction of millions of rejects: the {a} records budgeted buy an expected {b} of one hit, and seeing enough of them would take {c} coder-hours against the {d} the grant pays for. The design was not underpowered, it was unable in principle, and score-stratified oversampling only half-rescues it, because it finds the works the screen almost caught and stays blind to the ones it rejected confidently. Recall is now measured against the works that already carry rubric labels, and by known-item recall on a venue reference set. The first of those two instruments is itself limited, and finding 15 says how: rubric labels are a machine’s, so scoring against them measures agreement with a machine and not accuracy. This is the only item on this list that the project caught with its own instruments rather than having it pointed out, and the correction to it was caught the same way.',
      },
      rubric: {
        title: 'The pilot screen violated its own locked rubric',
        body: 'The locked rubric tells the screener what it will see: title, abstract, publication year, language, venue, OpenAlex topic and field, Canadian institutional affiliations, and funders. The harness sent the first four. Venue, topic, field, affiliations and funders were all withheld, four of them sitting in the sample file and dropped by a single line of code, and venue never extracted from the snapshot at all. Every headline number in the pilot therefore comes from a screen that did not follow its own instrument: it ran, in effect, as a title-and-abstract screen, which is also why the finding about title-only screening may be measuring a harness bug rather than a property of machine screening, and is reported with that caveat. It is not repaired by re-labelling the rubric to match the harness. That would be fitting the instrument to the data after seeing the data, which is the thing this project exists to object to.',
      },
    },

    boundTitle: 'What this design does not claim',
    boundBody:
      'Coverage is estimated within F, not over all Canadian metaresearch. Eligible works outside F, in particular scholarship indexed by neither OpenAlex nor Érudit, are not estimated by this design, and no claim about them is made. The audit answers "what did the pipeline miss inside the sources I claim to cover?" That is a bounded question, honestly answerable, rather than an unbounded one that would require pretending.',
  },

  about: {
    eyebrow: 'About',
    title: 'What this is, and who made it',
    lead:
      'MétaCan is a proposal to the Canadian Metaresearch Data Challenge, for the 2nd Canadian Open Science Conference at the University of Ottawa, 27–29 October 2026. The pilot is complete and the repository is public: the committee can run it today.',
    whyTitle: 'Why it is built this way',
    whyBody:
      'I once benchmarked an automated pipeline that linked funded trials to their publications against a reference standard built by two independent human reviewers. Whenever a candidate record reached the matcher, it was accurate: sensitivity 92.2%, PPV 94.3%. But its sensitivity overall was 44.5%: more than half the publications the reviewers found by hand were never retrieved at all. The loss was in retrieval, not matching, and no internal quality check would have caught it. MétaCan is built so that the same failure, if it occurs, is measured rather than concealed.',
    reflexTitle: 'Reflexivity',
    reflexBody:
      'I am an independent researcher with no institutional affiliation. I am therefore a member of the population this dataset structurally cannot see: affiliation-based country assignment fails on precisely such records, and most of the search space carries no affiliation string at all. The funder clause in the primary estimand and the non-retrieved stratum in the audit exist because of that failure mode. I have a personal stake in their working. I am also, on the primary estimand, plausibly in the dataset; I will not code any record in the validation sample that includes my own work.',
    ethicsTitle: 'Ethics and governance',
    ethicsBody:
      'The dataset describes living people, who are represented only by what they have published. No sensitive identity is inferred or released: no gender, ethnicity, Indigeneity, or other protected characteristic is imputed from names, affiliations, or text. Where Indigenous-governed data or communities are implicated, no derived labels are released and appropriate governance is sought rather than asserted: invoking OCAP® without an Indigenous partner would be compliance theatre. A public correction mechanism allows individuals to contest or amend records about them.',
    authorTitle: 'Author',
    authorRole: 'Independent researcher',
    linksTitle: 'Links',
    links: {
      repo: 'Repository: code, protocol, pilot, and every number on this site',
      protocol: 'Protocol: estimand, frame, rubric, audit design',
      rubric: 'Screening rubric: the locked coding instrument',
      proposal: 'Proposal: the two-page attachment',
      findings: 'Pilot findings: the numbers, with their raw JSON',
      challenge: 'Canadian Metaresearch Data Challenge',
    },
    citeTitle: 'Licence',
    citeBody: 'Code: MIT. Data and documentation: CC BY 4.0.',
  },

  footer: {
    project: 'MétaCan',
    tagline: 'A map of Canadian metaresearch',
    sources:
      'Figures derived from the MétaCan pilot against OpenAlex and the Érudit OAI-PMH endpoint. Raw responses archived in the repository.',
    methodology: 'Methods',
    findings: 'Findings',
    repo: 'Repository',
    protocol: 'Protocol',
  },
}

/**
 * The dictionary's shape is whatever the English tree is. Declaring `fr` as
 * `Dictionary` makes an untranslated key a compile error rather than an English
 * string leaking into the French UI, which, on this project in particular,
 * would be an embarrassing thing to ship.
 */
export type Dictionary = typeof en

const fr: Dictionary = {
  meta: {
    title: 'MétaCan : une carte de la métarecherche canadienne',
    description:
      "Une carte ouverte de la métarecherche canadienne, à provenance tracée et à couverture auditée. Chaque notice indiquera pourquoi elle a été repérée et à quel titre elle est canadienne, et un audit humain bilingue quantifiera ce que la chaîne de traitement a manqué.",
  },

  nav: {
    overview: "Vue d'ensemble",
    findings: 'Constats',
    methods: 'Méthodes',
    about: 'À propos',
    primary: 'Principale',
    toggleNav: 'Afficher ou masquer la navigation',
  },

  common: {
    skipToContent: 'Aller au contenu',
    of: 'sur',
    found: 'Repéré',
    missed: 'Non repéré',
    source: 'Source',
    consequence: 'Conséquence pour le devis',
    computed: 'Calculé le',
    caveat: 'Mise en garde',
    caveatQuoted: 'citée telle quelle depuis findings.json',
    readMethods: 'Lire la méthode',
    allFindings: 'Tous les constats',
    repository: 'Dépôt',
    langLabel: 'Langue',
    switchToFr: 'Passer au français',
    switchToEn: "Switch to English",
    withdrawn: 'retiré',
    allCorrections: 'Tous les rectificatifs',
    seeFinding: 'Voir le constat',
  },

  home: {
    eyebrow: 'Défi de données en métarecherche canadienne · projet pilote',
    live: 'pilote terminé',
    headA: 'Une carte de la métarecherche canadienne,',
    headB: "lucide sur ce qu'elle ne voit pas.",
    thesis:
      "Chaque notice de MétaCan indiquera pourquoi elle a été repérée et à quel titre elle est canadienne, et un audit humain bilingue quantifiera ce que la chaîne de traitement a manqué.",
    lead:
      "Cartographier une communauté de recherche à partir de métadonnées bibliographiques expose à une défaillance précise : on cartographie ce que le repérage a pu voir, puis on présente le résultat comme une carte du domaine. L'écart est rarement mesuré. Ce projet le mesure.",
    kpiEyebrow: 'Ce que le pilote a mesuré',
    kpiNote:
      "Chaque chiffre de ce site est lu depuis pilot/results/findings.json, régénéré par make pilot à partir des réponses d'API archivées dans le dépôt. Aucun n'est saisi à la main dans une page.",
    kpi: {
      topic_route_recall: {
        label: 'Du domaine, réellement trouvé',
        note: "la voie thématique en a manqué {a} sur {b} ; selon l'autre trieur, {c}",
      },
      affiliation_gap: {
        label: "Notices sans affiliation",
        note: "{a} sur {b} ne portent aucune chaîne d'affiliation brute",
      },
      language_gap: {
        label: 'Part du français',
        note: '{a} notices canadiennes sur {b} sont en français',
      },
      erudit: {
        label: 'Sources Érudit dans OpenAlex',
        note: "{a} ensembles OAI-PMH moissonnables qu'il ne voit pas",
      },
    },
    findingsEyebrow: "{n} analyses menées sur l'API OpenAlex en direct",
    findingsTitle: "Ce que le pilote a établi, et ce qu'il a écarté",
    findingsLead:
      "Chaque analyse visait à vérifier si le devis évident tenait la route. La plupart ont montré que non. L'une d'elles a écarté l'estimateur de couverture sur lequel ce projet devait initialement reposer ; les trois dernières retournent les instruments de la chaîne de traitement contre elle-même et mesurent la part du domaine qui lui échappe.",
    seeAll: 'Voir tous les constats',
    gapEyebrow: 'La limite, énoncée en tête plutôt qu’en fin de texte',
    gapTitle: 'Ce que nous ne voyons pas',
    gapTag: 'Hors base de sondage',
    gapLead:
      "La couverture est estimée à l'intérieur d'une base de sondage figée : OpenAlex et Érudit. Les travaux qu'aucune des deux sources n'indexe ne sont pas estimés par ce devis, et aucune affirmation n'est faite à leur sujet. L'audit répond à une question bornée, à laquelle on peut répondre honnêtement, plutôt qu'à une question sans bornes qui obligerait à faire semblant.",
    gapItems: [
      "Les travaux qu'indexent ni OpenAlex ni Érudit. Ils sont hors de la base de sondage : l'audit ne peut pas les échantillonner, et ce projet ne les estime pas.",
      "Les notices sans chaîne d'affiliation : la majorité de l'espace de recherche. L'attribution du pays par affiliation échoue précisément sur ces notices, dont celles des chercheuses et chercheurs sans affiliation.",
      "Les travaux francophones dont la revue n'est pas indexée par OpenAlex. La part du français que l'on mesure décrit la chaîne de traitement, non la production scientifique.",
      "Les traditions dont le vocabulaire n'est pas celui du domaine. Une ethnographie en études des sciences et des techniques, ou une étude en sciences de l'information sur les pratiques informationnelles, peut n'employer aucun des mots-clés et relever pleinement du domaine.",
    ],
    gapClosing:
      "Ce ne sont pas des réserves ajoutées à la fin. C'est la raison pour laquelle le devis comporte une clause de financement, un moissonnage d'Érudit, une strate de notices non repérées et un classificateur sémantique plutôt qu'une liste de mots.",
    ctaEyebrow: 'Ouvert par défaut',
    ctaTitle: 'Exécutez-le vous-même.\nAucun réseau requis.',
    ctaItems: [
      { k: 'Pilote', v: 'make pilot', note: "sur l'API OpenAlex en direct" },
      { k: 'Hors ligne', v: 'make pilot-offline', note: 'à partir des réponses archivées' },
      { k: 'Licence', v: 'MIT · CC BY 4.0', note: 'code · données et documentation' },
    ],
  },

  findings: {
    eyebrow: 'Constats du pilote',
    title: '{n} analyses, et le devis que chacune a imposé',
    lead:
      "Chaque chiffre ci-dessous est produit par un script de pilot/, exécuté sur l'API OpenAlex en direct, la réponse brute étant archivée sous pilot/raw/. On peut les redériver hors ligne, sans aucun réseau, avec make pilot-offline. OpenAlex change tous les jours : une requête d'API n'est donc pas un objet reproductible tant que la réponse elle-même n'est pas conservée.",
    barCaption:
      "Le sarcelle représente ce dont la chaîne de traitement rend compte. L'ambre représente ce dont elle ne rend pas compte.",

    correctionTag: 'Rectificatif',
    correctionA:
      "Une version antérieure de ce site mettait en tête {a} : les travaux repérés par la voie thématique, divisés par la taille du domaine qu'implique le taux de base.",
    correctionB:
      "Ce chiffre était faux, car un ensemble repéré et une taille réelle de domaine ne sont pas des quantités commensurables, et le rapport flattait le devis ; évalué directement selon la grille de tri, le rappel de la voie thématique s'établit à {b}, et son intervalle de confiance exclut entièrement l'ancien chiffre.",

    ci: 'IC à 95 % : de {lo} à {hi}',
    stat: {
      precision: 'Précision',
      swap: 'Changer de trieur déplace le domaine de',
      agreement: 'Les trieurs s’accordent sur',
      noAbstractRate: 'Métarecherche repérée sans résumé',
      hasAbstractRate: 'Avec résumé',
      grantMultiple: 'Fois la subvention',
      designTotal: 'Ce que coûte désormais le devis',
      recallScreenerA: 'Rappel de la voie, trieur A',
      recallScreenerB: 'Trieur B',
    },

    limitTag: 'Limité par le constat {n}',
    limit: {
      recallIsModelDependent:
        "Il s'agit du rappel évalué selon les étiquettes d'un seul trieur : on mesure donc l'accord avec une machine, et non l'exactitude. Évaluée selon l'autre trieur, la même voie n'obtient plus {a}, mais {b}. La conclusion tient, et même se renforce, puisque le second trieur juge la voie encore plus mauvaise ; le chiffre, lui, ne devient pas pour autant une mesure de la vérité. Seul l'échantillon probabiliste codé par des humains peut y prétendre, et il n'a pas encore été réalisé.",
    },

    chartEyebrow: 'Constat {n}, développé',
    chartTitle: 'La polysémie, terme par terme',
    chartLead:
      "Pour chaque terme, la part de ses occurrences canadiennes qui relèvent effectivement de l'espace thématique de la métarecherche. Le sens courant du mot noie son sens métascientifique ; plus le terme est générique, pire c'est. C'est pourquoi ces termes sont exclus du lexique.",
    chartAxis: 'Part des occurrences dans le sujet (%)',
    chartTooltipHits: 'occurrences seules',
    chartTooltipOnTopic: 'dans le sujet',

    missedEyebrow: 'Constat {n}, développé',
    missedTitle: 'Où la métarecherche manquée avait été classée',
    missedLead:
      "OpenAlex classe un travail selon ce dont il traite. Un article de métarecherche sur la qualité des comptes rendus dans les essais en cardiologie porte, à la lecture, surtout sur la cardiologie : il est donc classé en cardiologie, et non en scientométrie. Le domaine est invisible au repérage thématique précisément parce qu'il porte sur d'autres domaines, et plus une étude s'engage sérieusement dans la discipline qu'elle examine, plus sûrement elle s'y fond. Voici les domaines sous lesquels les travaux manqués ont le plus souvent été classés.",
    missedAxis: 'Travaux de métarecherche manqués par la voie thématique',
    missedTooltip: 'travaux manqués, classés ici',
    missedNote:
      "Les {n} domaines ci-dessus représentent {a} des {b} travaux manqués ; les autres sont dispersés plus finement encore. Tous sont de la métarecherche, et tous ont été classés comme autre chose.",

    items: {
      topics: {
        title: "Le domaine n'a pas de place dans la taxonomie",
        consequence:
          "Aucune voie de repérage ne peut à elle seule circonscrire le domaine. D'où trois voies, et une provenance consignée notice par notice indiquant pourquoi chaque travail a été repéré.",
        found: 'Thématiques nommant le domaine',
        missed: 'Thématiques ne le nommant pas',
      },
      affiliation_gap: {
        title: "Les métadonnées d'affiliation sont le plus souvent absentes",
        consequence:
          "Une règle fondée sur la seule affiliation pour définir « canadien » est structurellement défaillante, et pas seulement bruitée. D'où la clause de financement dans l'estimande principale, et un audit qui échantillonne la strate des notices non repérées.",
        found: "Avec chaîne d'affiliation brute",
        missed: 'Sans aucune',
      },
      erudit: {
        title: 'Érudit est invisible pour OpenAlex',
        consequence:
          "Une chaîne de traitement fondée sur OpenAlex seul ne peut même pas poser la question du caractère francophone du corpus. D'où le moissonnage OAI-PMH d'Érudit comme source à part entière, et une validation stratifiée par langue.",
        found: 'Sources Érudit appariées dans OpenAlex',
        missed: 'Ensembles OAI-PMH moissonnables qu’il ne voit pas',
      },
      language_gap: {
        title: 'La métarecherche francophone est presque introuvable',
        consequence:
          "La part du français n'est pas un fait sur la production scientifique canadienne ; c'est un fait sur la chaîne de traitement. D'où des performances rapportées séparément en français et en anglais, et un suréchantillonnage des notices françaises dans l'audit.",
        found: 'Français',
        missed: 'Anglais et autres langues',
      },
      polysemy: {
        title: 'Le repérage par mots-clés ne survit pas à la polysémie',
        consequence:
          "Le sens métascientifique d'un terme n'est pas séparable, sur le plan lexical, de son sens courant. D'où un tri sémantique, et l'exclusion de ces termes du lexique.",
        found: 'Dans le sujet',
        missed: 'Hors sujet : bruit que la requête ne peut filtrer',
      },
      canadian_linkage: {
        title: '« Canadien » recouvre trois questions distinctes',
        consequence:
          "Les trois sens désignent des ensembles différents, et les métadonnées de financement défavorisent les sciences sociales. D'où une seule estimande principale préspécifiée, rapportée en deux composantes, et deux règles de rechange préspécifiées.",
        found: 'Repérés par affiliation canadienne',
        missed: 'Portant sur le Canada, sans affiliation canadienne',
      },
      capture_recapture_fails: {
        title: 'La capture-recapture est ici sans valeur',
        consequence:
          "Nous l'avons exécutée, et elle échoue. Les voies sont endogènes : la case des non-observés n'est pas identifiée et l'estimation ne constitue même pas une borne inférieure sûre. Elle est remplacée par un audit probabiliste stratifié en deux phases, qui échantillonne directement la strate non repérée au lieu de l'inférer.",
        found: 'Réellement observés',
        missed: "Travaux fantômes inventés par l'estimateur",
      },
      openalex_is_metered: {
        title: "L'API est facturée à l'usage : la base de sondage ne peut être énumérée en direct",
        consequence:
          "Une chaîne de traitement qui réinterroge l'API à cette échelle n'est ni gratuite ni reproductible : un seul passage sur la base de sondage canadienne prend plus d'une semaine avec le forfait gratuit, et les réponses changent pendant qu'il s'exécute. D'où l'instantané épinglé, qui est à la fois économique et figé.",
        found: "Appels qu'offre une fenêtre gratuite de quota",
        missed: 'Appels restant dus pour un seul passage',
      },
      base_rate: {
        title: 'Le domaine a un taux de base, et donc un dénominateur',
        consequence:
          "Le tri d'un échantillon canadien non filtré selon la grille mesure la taille du domaine sans recourir à la moindre stratégie de recherche : une hypothèse dotée d'un dénominateur, que l'échantillon probabiliste codé par des humains viendra éprouver. Ce qu'il ne dit pas, c'est ce que le repérage a manqué. Diviser un ensemble repéré par cette estimation revient à comparer des choses de nature différente, et c'est exactement ce qu'une version antérieure de ce site a fait. Ce que le repérage a réellement manqué est mesuré directement selon la grille de tri, ci-dessous.",
        found: 'Triés dans le champ (T1 ou T2)',
        missed: 'Triés hors champ',
      },
      agreement: {
        title: 'Changez de trieur et le domaine double',
        consequence:
          "Désignez un modèle comme trieur et le taux de base prend une valeur ; désignez l'autre et il prend plus du double, ce qui fait passer le domaine de dizaines de milliers de travaux à des dizaines de milliers de plus. L'intervalle binomial publié ne contient pas l'estimation de l'autre modèle, et c'est là tout le constat : l'incertitude qui compte ici n'est pas l'erreur d'échantillonnage, c'est le choix de l'instrument. Les deux trieurs s'accordent bien sur la grande majorité des notices, mais ce chiffre est dominé par les rejets évidents et s'effondre précisément à la frontière contestée : il vient donc en second, et jamais seul. Lisez la mise en garde : ceci mesure les trieurs, non la vérité. Seul l'échantillon probabiliste codé par des humains peut s'en charger.",
        found: 'Accord sur inclusion / exclusion',
        missed: 'Désaccord : la frontière contestée',
      },
      base_rate_robustness: {
        title: 'Un tiers du corpus est trié sur le seul titre',
        consequence:
          "L'objection évidente au taux de base est que sa partition serait un amas de notices fraîchement versées : le taux mesurerait alors la recherche récente, et non la base de sondage. Cette objection ne tient pas : la partition penche vers l'ancien, et le taux est stable d'une époque à l'autre. Mais l'époque était la mauvaise covariable. Ce sur quoi la partition sélectionne, c'est la récupération des résumés, et là, le tri n'a plus rien de stable : là où le résumé manque, il repère moitié moins de métarecherche, et l'effet résiste à l'ajustement pour l'année de publication et pour la langue. Un tiers de la base de sondage est jugé sur son seul titre, et le tri y repère moitié moins. C'est un véritable problème de couverture, et c'est pourquoi l'audit est stratifié selon la présence d'un résumé. Deux affirmations que ce constat portait autrefois, il ne les porte plus. Il soutenait que l'aveuglement était différentiel selon la tradition et qu'il coûtait aux traditions adjacentes plusieurs fois ce qu'il coûte à la métarecherche centrale, et cette affirmation constituait toute la réponse de la proposition au critère d'inclusivité ; elle repose sur une case de quatre notices, l'interaction n'est pas significative, et elle est retirée. Il soutenait aussi que les notices sans résumé étaient plus anciennes et moins anglophones, ce qui en aurait fait le portrait exact d'Érudit ; elles sont plus récentes, et la strate est presque entièrement anglophone. Cette phrase est supprimée, et non atténuée. Un véritable problème de couverture ne prouve pas un problème différentiel, et ce constat ne fait plus semblant du contraire. Une dernière limite tient au constat lui-même et non à la chaîne de traitement : le dispositif de tri a silencieusement perdu une partie des notices qu'on lui avait soumises, et il les a perdues de façon non aléatoire selon la présence d'un résumé, c'est-à-dire sur la covariable même dont dépend tout ce qui précède. L'effet est donc mesuré sur un échantillon dont des notices sans résumé ont été retirées de façon sélective, et le sens de ce biais n'est pas présumé ici.",
        found: 'Avec résumé, que le tri peut lire',
        missed: 'Sans résumé, où il en repère moitié moins',
      },
      topic_route_recall: {
        title: "Le domaine est invisible au repérage thématique, parce qu'il porte sur d'autres domaines",
        consequence:
          "Mesurée directement selon la grille de tri plutôt que déduite d'un rapport, la voie thématique ne repère qu'une faible minorité de la métarecherche de l'échantillon, et une bonne part de ce qu'elle repère n'est pas de la métarecherche. Elle échoue pour une raison qui vaut bien au-delà du cas canadien : OpenAlex classe un travail selon ce dont il traite, si bien qu'un article de métarecherche sur la qualité des comptes rendus dans les essais en cardiologie porte, à la lecture, surtout sur la cardiologie, et c'est là qu'il est classé. Plus une étude s'engage sérieusement dans la discipline qu'elle examine, plus sûrement elle s'y fond. D'où un devis qui trie une base de sondage canadienne au lieu de repérer un corpus de métarecherche, et qui conserve les voies de repérage comme provenance au lieu de les ériger en filtre d'entrée.",
        found: 'Repérés par la voie thématique',
        missed: 'Métarecherche qu’elle a manquée',
      },
      screening_cost: {
        title: "Le préfiltre n'existait que parce que j'avais mal chiffré l'autre option",
        consequence:
          "Ce constat annonçait autrefois que trier deux fois toute la base de sondage selon la grille complète coûtait plusieurs fois la subvention, et c'est ce chiffre qui justifiait de placer un tri grossier à bas coût devant le tri proprement dit. Le chiffre était faux. La grille est une consigne système : elle est envoyée une fois par appel, et non une fois par notice, et les fichiers de lots du pilote regroupent eux-mêmes de nombreuses notices par appel, si bien que la grille s'amortit sur l'ensemble au lieu d'être facturée à chacune. Le coût était surestimé de plusieurs fois. Le chiffre honnête est en tête de cette fiche, et il dépasse toujours la subvention : le second trieur reste donc affecté à un échantillon stratifié plutôt qu'à la base entière, car le constat 10 montre que son produit est une mesure de processus et que les deux usages qu'on en fait sont des quantités d'échantillon. Acheter de la précision sur un nombre qui n'est pas l'estimande n'est pas une économie. Ce qui est supprimé, c'est le tri grossier. Il n'a jamais été une simple commodité : un préfiltre est une étape de repérage, et le constat 12 démontre que c'est précisément le repérage qui détruit ces cartes. La version antérieure de cette fiche le savait et soutenait que le préfiltre restait admissible, au motif que son rappel serait mesuré et non espéré. L'argument était juste ; il est aujourd'hui sans objet, car une fois l'arithmétique corrigée, le tri grossier n'économise presque rien et achète une étape de repérage dont ce projet n'a nul besoin. La grille complète s'applique donc à chaque notice de la base de sondage, le second trieur garde son échantillon, et le reste paie la personne qui code à la main, laquelle constitue l'étude. L'erreur était la mienne ; le devis qu'elle m'a fait adopter était le mien ; les deux sont consignés.",
        found: 'Ce que la subvention peut payer',
        missed: 'Ce que trier deux fois la base resterait à devoir',
      },
      audit_power: {
        title: "L'audit ne pouvait pas mesurer ce pour quoi il existe",
        consequence:
          "Tous les autres constats retournent les instruments contre la chaîne de traitement. Celui-ci les retourne contre l'étape de validation, et elle non plus ne tient pas. Échantillonner au hasard la masse des notices rejetées pour retrouver ce que le tri a écarté à tort ne fonctionne pas : les notices rejetées à tort sont une fraction infime de millions de rejets, si bien que l'échantillon prévu n'en attend même pas une, et qu'en trouver assez coûterait des années-personnes de codage que la subvention n'a pas. Suréchantillonner les notices dont le score frôle le seuil aide, sans suffire : on retrouve ainsi les travaux que le tri a presque retenus, tout en restant aveugle à ceux qu'il a rejetés avec assurance. Le constat 11 nomme l'exposition qui, elle, est mesurée : un tiers de la base de sondage ne porte aucun résumé, et le tri y repère déjà moitié moins. Un travail dont le titre ne porte aucun mot du vocabulaire du domaine est rejeté avec assurance plutôt que de justesse ; c'est là un mécanisme, non un écart mesuré, et ce site n'en revendique pas davantage, car l'écart différentiel selon la tradition qu'affirmait le constat 11 est retiré. L'angle mort n'en demeure pas moins non aléatoire, et il demeure ailleurs que là où un échantillon aléatoire irait regarder. Le rappel se mesure donc autrement, de deux façons : sur les travaux qui portent déjà les étiquettes complètes de la grille, et par un rappel sur cibles connues à partir d'un ensemble de revues de référence. La revue est un critère externe. Un article signé au Canada dans une revue de métarecherche relève du domaine par son lieu de publication, quel que soit le sujet apparent de son résumé : la revue échappe ainsi à cette « aboutness » qui met en échec aussi bien le repérage thématique que le tri sur le seul titre, et c'est le seul instrument capable de voir dans l'angle mort. C'est aussi, comme le consignent les rectificatifs ci-dessous, l'un des champs que la grille verrouillée exigeait depuis toujours et que le dispositif du pilote a silencieusement retenus : ce « nouvel » instrument consiste en partie à faire enfin ce que la grille prescrivait.",
        found: 'Heures de codage que la subvention paie',
        missed: "Heures de codage qu'exigerait l'audit naïf",
      },
      label_limits: {
        title: "Le chiffre phare n'est que l'avis d'un modèle, et la strate française ne compte qu'un seul travail",
        consequence:
          "Ce constat est né d'une attaque menée contre les correctifs eux-mêmes, et il porte deux fois. D'abord sur le chiffre phare. Le constat 14 érigeait en instrument général le principe suivant : évaluer n'importe quel filtre sur les travaux qui portent déjà les étiquettes de la grille. L'instrument est bon : il ne coûte rien et évite de chercher des aiguilles dans la masse des notices rejetées. Mais ces étiquettes sont celles d'une machine. Les prendre pour référence, c'est mesurer l'accord avec une machine, non l'exactitude, et le constat 10 avait déjà montré que cette quantité varie du simple au double lorsqu'on change de machine. Elle varie ici aussi : le rappel de la voie thématique évalué selon le second trieur est nettement inférieur à celui qu'on obtient avec le premier. La conclusion survit, et se durcit même, puisque le second trieur juge la voie encore plus mauvaise ; ce qui ne survit pas, c'est l'idée que le chiffre mis en tête de ce site serait une mesure de la vérité. Seul l'échantillon probabiliste codé par des humains y donne accès, et il n'a pas été réalisé. Ensuite, et plus gravement, sur la promesse d'inclusivité. Le pilote tout entier ne contient qu'un seul travail francophone relevant du champ. Estimer une sensibilité pour le français exigerait davantage de notices françaises codées que l'audit ne peut en payer : la strate française n'est donc pas sous-puissante, elle est sans puissance aucune, et aucune taille d'échantillon réaliste ne la sauve dans une base de sondage bâtie sur le seul OpenAlex. Ce n'est pas un fait sur la production scientifique canadienne, et il ne faut surtout pas le lire ainsi. Érudit ne correspond à aucune source d'OpenAlex : dans cette base de sondage, la littérature francophone n'est donc pas rare, elle en est largement absente. La puissance du volet français repose donc entièrement sur le moissonnage d'Érudit, que ce pilote a vérifié sans l'exécuter. La revendication portant sur le français est désormais énoncée comme une condition et non comme une promesse : si le moissonnage ne livre pas assez de métarecherche francophone pour estimer une sensibilité, la revendication sera retirée plutôt que maquillée. Tel est l'état honnête du critère d'inclusivité, et c'est la deuxième fois que ce projet doit réviser à la baisse sa réponse à ce critère.",
        found: "Notices françaises que l'audit peut coder",
        missed: 'Notices françaises qui manqueraient encore',
      },
    },
  },

  methods: {
    eyebrow: 'Protocole',
    title: "L'estimande, la base de sondage, les voies et l'audit",
    lead:
      "Version préliminaire du préenregistrement, à déposer sur OSF avant la construction de la base de sondage et avant tout repérage. La date d'enregistrement, la version de l'instantané OpenAlex et la date du moissonnage d'Érudit sont apposées à la publication et ne peuvent plus être modifiées ensuite.",

    estimandTitle: "L'estimande, arrêtée à l'avance",
    estimandLead:
      "La frontière du domaine est discutable. C'est une raison de trancher à l'avance et de le dire, non de remettre la décision à plus tard.",
    estimandPrimary: 'Principale : la métarecherche produite au Canada',
    estimandPrimaryBody:
      "Un travail est retenu s'il est trié T1 ou T2 et satisfait au moins l'une des conditions suivantes : CA-AFF, au moins une signature dont l'affiliation institutionnelle se trouve au Canada ; ou CA-FUND, au moins un organisme subventionnaire parmi les IRSC, le CRSNG, le CRSH et la FCI. Les deux composantes sont rapportées séparément autant que conjointement, parce que les métadonnées de financement défavorisent les sciences sociales et qu'un chiffre agrégé le masquerait.",
    estimandSecondary: 'Secondaire : la métarecherche portant sur le système de recherche canadien',
    estimandSecondaryBody:
      "Quelle que soit la localisation des auteurs, repérée par tri plutôt que par mot-clé.",
    estimandDescriptive: "Attributs descriptifs, et non critères d'inclusion",
    estimandDescriptiveBody:
      "CA-VENUE (publication dans une revue canadienne, y compris hébergée par Érudit) et CA-PERSON (une personne signataire ayant déjà eu une affiliation canadienne connue) sont consignés sur chaque notice et ne servent jamais à en admettre une. Un article de portée générale qui paraît dans une revue canadienne n'est pas pour autant de la métarecherche canadienne. Ce sont d'intéressantes covariables et de piètres gardiens.",
    estimandAlts:
      "Deux règles de rechange sont préspécifiées afin d'éprouver les conséquences de cette décision : ALT-1 (stricte) retient CA-AFF seul ; ALT-2 (large) ajoute CA-VENUE et CA-PERSON à la règle principale. Seules ces deux-là seront rapportées. Énumérer toutes les combinaisons de cinq indicateurs binaires, ce sont des degrés de liberté du chercheur déguisés en analyse de sensibilité.",

    frameTitle: 'La base de sondage (F), figée avant tout repérage',
    frameLead:
      "F est définie et figée avant le repérage, et toute affirmation de cette étude est bornée à F.",
    frameSources: 'Sources',
    frameSourcesBody:
      "Un instantané épinglé d'OpenAlex (et non l'API en direct, qui change tous les jours et rendrait l'étude irreproductible), ainsi qu'un moissonnage OAI-PMH épinglé d'Érudit, dont la date est apposée.",
    frameWindow: 'Fenêtre',
    frameWindowBody: 'Années de publication 2000 à 2025 inclusivement.',
    frameMembership: 'Appartenance',
    frameMembershipBody:
      "Une notice entre dans F si elle satisfait l'une quelconque des conditions suivantes : une affiliation canadienne ; un organisme subventionnaire canadien ; une mention du Canada dans le titre ou le résumé, en anglais ou en français ; une thématique candidate ; une correspondance avec le lexique bilingue ; une signature figurant dans le corpus d'amorçage ; ou le fait d'être une notice Érudit.",
    frameWhy:
      "F est délibérément trop large et de faible précision. Sa raison d'être n'est pas de constituer la réponse, mais un univers énumérable à l'intérieur duquel la strate non repérée peut être échantillonnée. Une base de sondage réduite à « tout OpenAlex » ne peut pas être échantillonnée utilement, et une base de sondage qui coïncide avec l'ensemble repéré ne peut pas mesurer ce que le repérage a manqué.",

    routesTitle: 'Trois voies, avec provenance',
    routesLead:
      "Aucune voie ne circonscrit à elle seule le domaine : chaque notice conserve donc l'ensemble des voies qui l'ont repérée. Le recouvrement entre voies et le rendement marginal de chacune sont rapportés à titre descriptif. Ils ne servent pas à estimer la population non observée.",
    routes: [
      {
        id: 'R1',
        name: 'Structurée',
        body: "Thématiques candidates et liste de revues constituée à la main, en anglais et en français.",
      },
      {
        id: 'R2',
        name: 'Lexicale et sémantique',
        body: "Un lexique bilingue, complété par la similarité de plongements multilingues avec le corpus d'amorçage. Interlingue par construction : la vraie réponse au français, et non une liste de mots greffée sur une liste anglaise.",
      },
      {
        id: 'R3',
        name: 'Boule de neige',
        body: "Un corpus d'amorçage constitué à la main, puis ses voisins de citation, en amont comme en aval.",
      },
    ],

    tiersTitle: 'Niveaux de tri',
    tiersLead:
      "La question est de savoir si l'objet d'étude est la recherche elle-même. Un essai clinique en cardiologie n'est pas de la métarecherche. Une étude de la façon dont les essais en cardiologie rapportent leurs résultats en est. Le critère est ce sur quoi porte le travail, non le domaine où il paraît ni le vocabulaire qu'il emploie.",
    tiers: [
      {
        id: 'T1',
        name: 'Métarecherche centrale',
        body: "L'objet d'étude premier est la recherche elle-même : ses méthodes, ses comptes rendus, sa reproductibilité, son intégrité, la révision par les pairs, son évaluation, son financement, sa main-d'œuvre, la communication savante (modèles de publication, libre accès, science ouverte, prépublications), ou la méthodologie de la synthèse des données probantes.",
      },
      {
        id: 'T2',
        name: 'Adjacent',
        body: "Des travaux sur la science comme système social qui ne se réclament pas de la métarecherche mais l'étudient : études des sciences et des techniques, sciences de l'information et des bibliothèques, infrastructures de recherche, politiques scientifiques. C'est en T2 que vit la diversité du domaine. Il faut y être généreux.",
      },
      {
        id: 'T3',
        name: 'Contextuel',
        body: "Éditoriaux, commentaires, documents de politique, annonces d'infrastructure. Cartographiés et diffusés, jamais versés au corpus analytique.",
      },
      {
        id: 'OUT',
        name: 'Hors métarecherche',
        body: "Tout le reste. Une étude qui emploie une méthode n'est pas une étude de cette méthode : une méta-analyse répondant à une question clinique est hors champ ; une étude de la façon dont les méta-analyses traitent l'hétérogénéité est T1.",
      },
    ],
    errorsTitle: 'Les trois erreurs qui comptent le plus',
    errors: [
      {
        name: 'La polysémie',
        body: "Dans un article de biochimie, « reproductibilité » signifie que le dosage donne deux fois la même lecture. Dans un article de métarecherche, le mot désigne la crise de la reproductibilité. Seul le second sens est dans le champ. Il faut juger le sens, non le mot.",
      },
      {
        name: "La méthode et l'objet",
        body: "Employer la bibliométrie n'équivaut pas à étudier la recherche. Il faut se demander : si cet article dit vrai, sur quoi en savons-nous davantage, sur une question scientifique ou sur la pratique de la science ? Dans le premier cas, il est hors champ.",
      },
      {
        name: "L'absence de vocabulaire n'est pas l'absence de contenu",
        body: "Un article d'études des sciences sur les pratiques de laboratoire, ou un article en sciences de l'information sur la façon dont on repère les données, peut n'employer aucun mot-clé du domaine et relever pleinement du niveau T2. Il ne faut pas exiger le vocabulaire. C'est l'erreur qui fait paraître le domaine plus petit et plus anglophone qu'il ne l'est.",
      },
    ],

    auditTitle: 'Validation : un audit probabiliste stratifié en deux phases',
    auditLead:
      "Le cœur de l'étude, et ce que le domaine escamote d'ordinaire. La capture-recapture n'est pas utilisée, et c'est une décision réfléchie plutôt qu'un oubli.",
    auditSteps: [
      {
        n: 'Phase 1',
        name: 'Partitionner et échantillonner',
        body: "Partitionner F entre notices repérées et non repérées. Tirer de chacune un échantillon probabiliste stratifié, à probabilités de sélection connues et consignées. Les strates croisent la langue, la source, la partition et la tranche de score du classificateur. On suréchantillonne les notices françaises, les notices d'Érudit, le matériel adjacent en études des sciences et en sciences de l'information, les notices non repérées à score élevé (là où se concentrent les manques), ainsi que les provinces et les genres sous-représentés.",
      },
      {
        n: 'Phase 2',
        name: 'Coder à l’aveugle, puis arbitrer',
        body: "Deux personnes codent chaque notice échantillonnée de façon indépendante, à l'aveugle quant au score du classificateur et l'une par rapport à l'autre, selon une grille de tri verrouillée. Les désaccords sont arbitrés au regard de la grille et les décisions sont consignées. Le classificateur ne participe en rien à la construction de l'étalon de référence qui le juge. La deuxième personne codeuse doit être bilingue pour la strate française ; si aucune personne francophone n'est recrutée, les estimations de cette strate sont retirées, et non imputées.",
      },
      {
        n: 'Estimation',
        name: 'Pondérée par le plan de sondage',
        body: "Au moyen de poids inversement proportionnels à la probabilité de sélection : la sensibilité du repérage à l'intérieur de F (la quantité maîtresse, et la réponse à « qu'avons-nous manqué ? ») ; la précision et le rappel du tri, avec les effectifs de la matrice de confusion ; le nombre de travaux admissibles dans F, avec intervalle de confiance ; et l'erreur différentielle selon la langue, la source, la tradition, le genre et le type de lien canadien. Ce dernier point est l'essentiel : pour qui la chaîne de traitement échoue, et pas seulement à quelle fréquence.",
      },
    ],
    crTitle: 'Pourquoi la capture-recapture a été écartée',
    crBody:
      "Les voies sont endogènes. La boule de neige dépend du corpus d'amorçage, et toute expansion par auteur dépend des auteurs mis au jour par les autres voies. Les modèles log-linéaires à listes multiples ne peuvent pas identifier la case des non-observés sans une restriction invérifiable sur l'interaction d'ordre le plus élevé, et avec des listes construites de façon endogène cette restriction n'est pas crédible. L'estimation ne constitue pas non plus une borne inférieure sûre : selon la structure de dépendance, elle peut surestimer la population non observée aussi bien que la sous-estimer. L'estimateur naïf renvoie un chiffre qui impliquerait que le Canada produit la majeure partie de la métarecherche mondiale. La seule borne inférieure inconditionnelle sur la population, c'est le nombre de travaux admissibles effectivement observés, et c'est ce qui sera rapporté. L'audit remplace l'estimateur parce qu'il échantillonne l'écart au lieu de l'inférer.",
    correctionsTitle: 'Rectificatifs',
    correctionsLead:
      "Toute erreur relevée dans ce projet est consignée dans DEVIATIONS.md, avant le dépôt, avec la date à laquelle elle a été trouvée et la suite qui lui a été donnée. Le protocole l'exige : réviser en silence constitue en soi un manquement à l'intégrité scientifique, et il s'agit ici d'un projet de métarecherche. Les six ci-dessous sont celles qu'une personne lisant ce site aurait autrement prises pour argent comptant : elles figurent donc ici, et non dans un fichier que personne n'ouvre. Chacune a été mise au jour par un examen adverse ou par les instruments mêmes du projet, et aucune n'a été discrètement fondue dans une réécriture.",
    correctionsLinkNote: 'chaque écart, avec sa date et sa raison',
    correctionsTag: 'Rectifié',
    correctionsClosing:
      "Deux de ces rectificatifs ont modifié le devis, et non la seule prose. L'erreur de coût est ce qui avait placé un préfiltre à bas coût devant le tri : corriger l'erreur a supprimé le préfiltre. La violation de la grille signifie que les chiffres du pilote proviennent d'un tri qui n'a vu que six des huit champs prescrits par son propre instrument ; l'étude complète réexécute donc le tri avec la charge utile intégrale et rapporte l'écart entre les deux exécutions comme un constat à part entière : ce que valaient les métadonnées retenues. C'est une mesure que personne ne fait d'ordinaire, et elle n'existe que parce que l'anomalie a eu lieu.",
    correctionsItems: {
      coverage: {
        title: 'Le chiffre de couverture que ce site mettait en tête',
        body: "Le pilote annonçait {a} : les travaux repérés par la voie thématique, divisés par la taille du domaine qu'implique le taux de base. Cela revient à diviser un ensemble repéré par une taille réelle de domaine. Les deux quantités ne sont pas commensurables, l'ensemble repéré n'est ni entièrement de la métarecherche ni un tirage aléatoire du domaine, et le rapport n'avait aucune estimande derrière lui. Il flattait le devis, et c'est ainsi qu'il a survécu si longtemps. La bonne quantité est le rappel, mesuré directement selon les étiquettes de la grille : {b}, dont l'intervalle exclut entièrement l'ancien chiffre.",
      },
      differential: {
        title: 'La perte différentielle des traditions adjacentes',
        body: "On affirmait que le tri perdait les traditions adjacentes (études des sciences, sciences de l'information) à {a}, contre {b} pour la métarecherche centrale. C'était là toute la réponse de la proposition au critère d'inclusivité : faute de pouvoir représenter les traditions du domaine, je pouvais au moins mesurer à quel point je les servais mal. La case sur laquelle cela repose compte {c} notices, et le test d'interaction, seul test qui demande si les deux pertes diffèrent le moins du monde, donne p = {d}. On ne peut pas les distinguer. L'affirmation différentielle est retirée. L'effet principal sur lequel elle était bâtie subsiste, et il constitue un véritable problème de couverture, mais il ne prouve pas un aveuglement différentiel selon la tradition.",
      },
      erudit_profile: {
        title: "« Les résumés manquants concernent des notices plus anciennes et non anglophones : le portrait exact d'Érudit »",
        body: "Faux sur les deux points. Les travaux sans résumé sont plus récents, et non plus anciens ({b} contre {c}), et la strate est anglophone à {a} : ce sont donc les travaux de langue anglaise qui ont le plus de chances de manquer de résumé ({d} contre {e}). La phrase déduisait la signature d'une plateforme francophone d'une strate presque entièrement anglophone. Elle était de surcroît codée en dur, sous forme de prose, dans un script dont le propre commentaire, trois lignes plus haut, qualifiait d'indéfendable, dans un projet de métarecherche, le fait de coder en dur une telle direction. La phrase est supprimée, et non atténuée.",
      },
      cost: {
        title: "Le coût du tri, et le préfiltre qu'il a fait acheter",
        body: "Trier deux fois la base de sondage selon la grille complète avait été chiffré à {a}, en facturant la grille une fois par notice. Or la grille est une consigne système, envoyée une fois par appel, et les fichiers de lots du pilote regroupent eux-mêmes de nombreuses notices par appel : elle s'y amortit, et la facture était surestimée de {c}. Le chiffre honnête est {b}. L'erreur n'était pas cosmétique. C'est elle qui justifiait un tri grossier à bas coût devant le tri proprement dit, et un tri grossier est une étape de repérage dans un projet dont le constat central est que c'est le repérage qui détruit ces cartes. Une fois l'arithmétique corrigée, le tri grossier n'économise presque rien. Il est supprimé, et la grille complète s'applique désormais à chaque notice de la base de sondage, le second trieur restant sur un échantillon, pour {d}.",
      },
      audit: {
        title: "Le devis d'audit ne pouvait pas mesurer ce que mesure un audit",
        body: "La validation devait échantillonner au hasard la masse des notices rejetées et compter ce que le tri avait écarté à tort. Ces travaux sont une fraction infime de millions de rejets : les {a} notices prévues n'achètent que {b} occurrence attendue, et en observer assez exigerait {c} heures de codage contre les {d} que paie la subvention. Le devis n'était pas sous-puissant : il était impuissant par construction, et le suréchantillonnage stratifié par score ne le sauve qu'à moitié, puisqu'il retrouve les travaux que le tri a presque retenus et reste aveugle à ceux qu'il a rejetés avec assurance. Le rappel se mesure désormais sur les travaux qui portent déjà les étiquettes de la grille, et par un rappel sur cibles connues à partir d'un ensemble de revues de référence. Le premier de ces deux instruments est lui-même limité, et le constat 15 dit en quoi : les étiquettes de la grille sont celles d'une machine, si bien que les prendre pour référence revient à mesurer l'accord avec une machine et non l'exactitude. C'est le seul point de cette liste que le projet ait décelé avec ses propres instruments, sans qu'on le lui signale, et le correctif qui s'y applique a été trouvé de la même façon.",
      },
      rubric: {
        title: 'Le tri du pilote a enfreint sa propre grille verrouillée',
        body: "La grille verrouillée annonce au trieur ce qu'il verra : le titre, le résumé, l'année de publication, la langue, la revue, la thématique et le domaine OpenAlex, les affiliations institutionnelles canadiennes et les organismes subventionnaires. Le dispositif n'a transmis que les quatre premiers. La revue, la thématique, le domaine, les affiliations et les financements ont tous été retenus : quatre d'entre eux se trouvaient dans le fichier d'échantillon et ont été écartés par une seule ligne de code, et la revue n'a jamais été extraite de l'instantané. Chaque chiffre marquant du pilote provient donc d'un tri qui n'a pas suivi son propre instrument : il s'est exécuté, de fait, comme un tri sur titre et résumé. C'est aussi pourquoi le constat portant sur le tri au seul titre mesure peut-être une anomalie du dispositif plutôt qu'une propriété du tri automatique, et il est rapporté avec cette réserve. On ne répare pas cela en réétiquetant la grille pour qu'elle corresponde au dispositif : ce serait ajuster l'instrument aux données après les avoir vues, ce à quoi ce projet existe précisément pour s'opposer.",
      },
    },

    boundTitle: 'Ce que ce devis ne prétend pas',
    boundBody:
      "La couverture est estimée à l'intérieur de F, et non sur l'ensemble de la métarecherche canadienne. Les travaux admissibles hors de F, en particulier ceux qu'indexent ni OpenAlex ni Érudit, ne sont pas estimés par ce devis, et aucune affirmation n'est faite à leur sujet. L'audit répond à la question : « qu'est-ce que la chaîne de traitement a manqué à l'intérieur des sources dont je revendique la couverture ? » C'est une question bornée, à laquelle on peut répondre honnêtement, plutôt qu'une question sans bornes qui obligerait à faire semblant.",
  },

  about: {
    eyebrow: 'À propos',
    title: "Ce qu'est ce projet, et qui l'a réalisé",
    lead:
      "MétaCan est une proposition soumise au Défi de données en métarecherche canadienne, dans le cadre de la 2e Conférence canadienne sur la science ouverte, à l'Université d'Ottawa, du 27 au 29 octobre 2026. Le pilote est terminé et le dépôt est public : le comité peut l'exécuter dès aujourd'hui.",
    whyTitle: "Pourquoi le projet est conçu ainsi",
    whyBody:
      "J'ai déjà évalué une chaîne automatisée qui reliait des essais cliniques financés à leurs publications, en la comparant à un étalon de référence construit par deux réviseurs indépendants. Chaque fois qu'une notice candidate parvenait à l'appariement, celui-ci était juste : sensibilité de 92,2 %, valeur prédictive positive de 94,3 %. Mais sa sensibilité globale n'était que de 44,5 % : plus de la moitié des publications trouvées à la main par les réviseurs n'avaient jamais été repérées. La perte se situait au repérage, non à l'appariement, et aucun contrôle de qualité interne ne l'aurait décelée. MétaCan est conçu pour que la même défaillance, si elle survient, soit mesurée plutôt que dissimulée.",
    reflexTitle: 'Réflexivité',
    reflexBody:
      "Je suis chercheur indépendant, sans affiliation institutionnelle. J'appartiens donc à la population que ce jeu de données est structurellement incapable de voir : l'attribution du pays par affiliation échoue précisément sur de telles notices, et la majeure partie de l'espace de recherche ne porte aucune chaîne d'affiliation. La clause de financement dans l'estimande principale et la strate non repérée de l'audit existent à cause de ce mode de défaillance. J'ai un intérêt personnel à ce qu'elles fonctionnent. Selon l'estimande principale, je figure aussi plausiblement dans le jeu de données ; je ne coderai aucune notice de l'échantillon de validation qui porte sur mes propres travaux.",
    ethicsTitle: 'Éthique et gouvernance',
    ethicsBody:
      "Le jeu de données décrit des personnes vivantes, qui n'y sont représentées que par ce qu'elles ont publié. Aucune identité sensible n'est inférée ni diffusée : ni genre, ni origine ethnique, ni autochtonie, ni autre caractéristique protégée n'est déduite des noms, des affiliations ou du texte. Lorsque des données ou des communautés autochtones sont en cause, aucune étiquette dérivée n'est diffusée et une gouvernance appropriée est recherchée plutôt qu'affirmée : invoquer les principes PCAP® sans partenaire autochtone relèverait du théâtre de la conformité. Un mécanisme public de correction permet à chacun de contester ou de faire modifier les notices qui le concernent.",
    authorTitle: 'Auteur',
    authorRole: 'Chercheur indépendant',
    linksTitle: 'Liens',
    links: {
      repo: 'Dépôt : code, protocole, pilote, et chaque chiffre de ce site',
      protocol: "Protocole : estimande, base de sondage, grille de tri, devis d'audit",
      rubric: 'Grille de tri : l’instrument de codage verrouillé',
      proposal: 'Proposition : le document de deux pages',
      findings: 'Constats du pilote : les chiffres, avec leur JSON brut',
      challenge: 'Défi de données en métarecherche canadienne',
    },
    citeTitle: 'Licence',
    citeBody: 'Code : MIT. Données et documentation : CC BY 4.0.',
  },

  footer: {
    project: 'MétaCan',
    tagline: 'Une carte de la métarecherche canadienne',
    sources:
      "Chiffres issus du pilote MétaCan, exécuté sur OpenAlex et sur le point d'accès OAI-PMH d'Érudit. Réponses brutes archivées dans le dépôt.",
    methodology: 'Méthodes',
    findings: 'Constats',
    repo: 'Dépôt',
    protocol: 'Protocole',
  },
}

export const dictionaries: Record<Lang, Dictionary> = { en, fr }
